//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaShoppe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_User
    {
        public string email_address { get; set; }
        public string password_hash { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> last_reset { get; set; }
        public int adminID { get; set; }
    }
}
