//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaShoppe.Domain.Concrete
{
    using PizzaShoppe.Domain.Concrete;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pizzaEntities : DbContext
    {
        public pizzaEntities()
            : base("name=pizzaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appetizer> Appetizers { get; set; }
        public virtual DbSet<Beverage> Beverages { get; set; }
        public virtual DbSet<PizzaShoppe.Domain.Concrete.Crust> Crusts { get; set; }
        public virtual DbSet<SpecialtyPizza> SpecialtyPizzas { get; set; }
        public virtual DbSet<Topping> Toppings { get; set; }
    }
}
