//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaShoppe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialtyPizza
    {
        public int PizzaID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal SmallPrice { get; set; }
        public decimal MedPrice { get; set; }
        public decimal LargePrice { get; set; }
        public string Size { get; set; }
    }
}
